### ISSUE TITLE
`install latest` does not work (with `ipfs daemon` on)

### ISSUE THREAD

**Issue by jbenet** [ipfs/ipfs-update#53]
```
> ipfs-update install latest
ERROR: error resolving 'latest':  cat: Failed to get block for QmQdRJSSxhpVv2vKREGBrhmCTysZLW11AFcm6DnsVwhxtA: context deadline exceeded
```

**Comment by jbenet** [comment]
- when running ipfs.
- if ipfs is off, `install latest` works.

**Comment by jbenet** [comment]
- ipfs-update SHOULD work with `ipfs daemon` on. it should: 
  - use ipfs to download the next version (caching)
  - shut down the daemon
  - update
  - turn on daemon again.

not sure how this plays with people's service starters, etc. maybe we should make `ipfs daemon` check + wait for a repo update to finish (so if user's system starts it again it's not interfering).

---

for now, let's make `ipfs-update` ask the user to turn off `ipfs daemon` or something. the current UX is borked.

**Comment by whyrusleeping** [comment]
@jbenet I think this is because your current daemon was borked for some reason. ipfs-update should work just fine with a running daemon (and will use it for downloading things).

We should probably add an `--ingore-local-daemon` flag or something for the case where we want to default to http gateways for the download for some reason
