### ISSUE TITLE
Cannot install ipfs in Linux after installing with go

### ISSUE THREAD

**Issue by renatoathaydes** [ipfs/ipfs-update#73]
I ran the following command to get `ipfs-update`:

```
go get -u github.com/ipfs/ipfs-update
```

This worked and correctly installed `ipfs-update` on my `~/go/bin` folder.

I then put that path in my `PATH` to be able to run `ipfs-update` from anywhere.

I then tried to install `ipfs` by running this command:

```
ipfs-update install v0.4.13
```

Which outputs this error:

```
fetching go-ipfs version v0.4.13
binary downloaded, verifying...
success! tests all passed.
install failed, reverting changes...
ERROR: could not find good install location 
```

I don't think there's any environment issues on my machine, maybe you just didn't test this on Ubuntu before?

My system is a Ubuntu 16.04 LTS 64-bit and I have plenty of RAM (16GB) and disk space (at least 400GB free).

**Comment by renatoathaydes** [comment]
Looking at `install.go`, looks like it expects my `https://golang.org/doc/code.html#GOPATH` environment variable to be set, but I just leave it empty so Go uses the default (see the link) which should be `~/go`.

I can make a PR adding this path to the `candidates` so you don't go trying to install in protected paths like `/usr/bin` before trying that one :)

**Comment by renatoathaydes** [comment]
Tested my changes, the installation works now.

**Comment by whyrusleeping** [comment]
@renatoathaydes Ah, thanks! It looks like we didnt anticipate the default GOPATH change that was introduced in go1.9, thats bit us in a few places now.

**Comment by renatoathaydes** [comment]
I'll track down all places in `ipfs-update` and change them as well... should I push to the same branch? or new PR?

**Comment by whyrusleeping** [comment]
You can push to the same branch, no problem

**Comment by renatoathaydes** [comment]
I only found one more usage, and it was in a function that is not used within the `ipfs-update` project: `getMigrationsGoGet`. There can be many GOPATH paths, but as in this case it expected one, I just used the first one. Hope that's ok for now at least (you should check if the actual file exists, and if not, try the second and third and so on...)

**Comment by wiz** [comment]
An option to set install path explicitly would be most welcome.

**Comment by klueq** [comment]
So the fix is to add the following line to `~/.bashrc`:

```
export PATH=$PATH:~/go/bin
```

Then restart the bash terminal.

I'm sorry for being harsh, but I think it's astonishing that such basic fundamental things don't work out of the box and people have to spend time fixing intricate relationship problems between some internal components of the ipfs update tool. There should be a daily script run on a VM that gets ipfs-update, installs the latest ipfs and does some basic stuff to prove it's working.

**Comment by djdv** [comment]
Can people encountering this issue let me know if this resolves it for you?
https://github.com/djdv/ipfs-update/tree/install-path-fix

**Comment by Mikaela** [comment]
I think there is some reason why `export PATH=...` is a bad idea, but I cannot remember what, and I would use `PATH=$HOME/go/bin:$PATH` and in case duplicates were a problem¸ https://unix.stackexchange.com/a/14896 another line for bashrc to fix it.

**Comment by ThomasFreedman** [comment]
I'm getting this 'no good location' error and my GOPATH env is set. How does "ipfs-update install ipfs latest" determine what a "good" location is? I'm running with sudo, so it isn't a permissions issue.

And yes, the docs need some help. [this page](https://docs.ipfs.io/guides/guides/install/#installing-with-ipfs-update) has contradictory info, as it says under **Getting ipfs-update** to use "go get -u ..." and under **Building from Source** go get no longer works (which I found to be true).

I'm working on the Raspberry Pi 3B platform (April 8th Raspbian Lite OS version). The siderus repo (to install ipfs with apt-get) no longer works either, which is why I switched to using ipfs-update.

Another thing to consider with "install latest" is it is truly the latest, which right now is an release candidate. Would be great to have a way to get  the latest non RC version. Something to think about for production environments.
